export const properties = [
  {
    id: 1,
    slug: 'paranhos-apartment',
    mapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1501.3463993945666!2d-8.609939604577535!3d41.184867156661596!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd24643159ecaf3f%3A0xdff04d905b4d5e7d!2s4200-550%20Porto!5e0!3m2!1spt-PT!2spt!4v1777896555430!5m2!1spt-PT!2spt',
    bookingLinks: {
      idealista: 'https://www.idealista.pt/imovel/34457200/',
      airbnb: 'https://www.airbnb.com/users/profile/1470751082133656177?previous_page_name=PdpHomeMarketplace&locale=en&_set_bev_on_new_domain=1776797230_KKmE2MPABYjMTzwz&set_everest_cookie_on_new_domain=1776797229.EAYjVlMDU4YTQxMTA5OT.avGC8Xz-NKOetkvjxPDv0QzwxblIexDsUiWpxelMv_k',
      spotahome: 'https://www.spotahome.com/porto/for-rent:apartments/1491376',
      flatio: 'https://www.flatio.es/alquiler/piso/120808-oporto',
    },
    price: '1,350',
    name: 'Paranhos',
    subtitle: 'Ultra-Modern Urban Apartment',
    location: 'Paranhos, Porto',
    description:
      'One of the most modern-looking buildings you will find in Porto, embodying a minimalistic approach that combines a clean architectural exterior with a functional, elegant, and high-standard interior. Located in Paranhos, a privileged location due to its direct access to the city center, the University Polo, shopping hubs, major healthcare facilities, and diverse dining options.',
    longDescription:
      'One of the most modern-looking buildings you will find in Porto, embodying a minimalistic approach that combines a clean architectural exterior with a functional, elegant, and high-standard interior. Located in Paranhos, a privileged location due to its direct access to the city center, the University Polo, shopping hubs, major healthcare facilities, and diverse dining options.',
    tags: [
      { type: 'people', count: 2 },
      'Garage',
      'Privileged Location',
      'Wide Space',
      'Ultra-Modern',
      'Fully Furnished & Equipped',
      'Quiet & Soundproof',
      'Double-Glazed Windows',
    ],
    specs: {
      area: '60',
      beds: '1',
      baths: '1',
      type: 'Apartment',
      status: 'For Rent',
      year: '2023',
      floor: '3',
      rooms: '4',
      garage: '1 Spot',
    },
    image: '/images/Website.images/apt.photos/paranhos.apt/1.webp',
    gallery: Array.from({ length: 20 }, (_, i) => `/images/Website.images/apt.photos/paranhos.apt/${i + 1}.webp`),
    moreDetails: {
      intro: [
        'Fully furnished and equipped apartment, ideal for professionals, expatriates, international students, and digital nomads looking for comfort, functionality, and a turnkey solution in Porto.',
        'Located in Paranhos, in a central and dynamic area with a strong university presence, close to hospitals, faculties, commerce, and public transport (metro and buses), allowing quick access to the city center.',
        'The social area in open space integrates the living room, dining area, and a space dedicated to teleworking by the window, with excellent natural light throughout the day.',
        'Perfect for those looking for a flexible housing solution, with services included, parking, and excellent connection to the entire city of Porto.',
      ],
      characteristics: [
        'Flexible lease from 1 to 12 months',
        'Fully furnished and equipped apartment',
        'Air conditioning, heating and double-glazed Windows',
        'High-speed internet and television',
        'Fortnightly cleaning included',
        'Expenses included up to €150/month (water, electricity, and internet)',
      ],
      composition: [
        '1 bedroom with double bed and built-in wardrobes with interior lighting',
        'Dedicated teleworking space by the window',
        'Open space social area with living room and dining zone',
        'Fully equipped kitchen (stove, oven, refrigerator, dishwasher)',
        'Laundry area with washing machine and dryer',
        '1 full bathroom with shower and contemporary finishes',
        '1 parking space included in the building',
      ],
      highlights: [
        'Excellent natural luminosity',
        'Modern and functional design',
        'Double-glazed windows for thermal comfort',
        'Strategic location near the University Campus and hospitals',
        'Bed linen and towels included',
      ],
      conditions: [
        'Deposit: 1 month (returned up to 30 days after departure)',
        'Administrative fee: €135 (one-time payment at the start of the contract)',
        'Fixed-term contract (not automatically renewable)',
      ],
    },
  },
  {
    id: 2,
    slug: 'matosinhos-apartment',
    mapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1814.2561436565452!2d-8.692038358446707!3d41.18608973309975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd246f31b43ed1f5%3A0xa60c6b18bce815c8!2s4450-038%20Matosinhos!5e0!3m2!1spt-PT!2spt!4v1777896408666!5m2!1spt-PT!2spt',
    bookingLinks: {
      idealista: 'https://www.idealista.pt/imovel/34888612/',
      airbnb: 'https://www.airbnb.com/users/profile/1470751082133656177?previous_page_name=PdpHomeMarketplace&locale=en&_set_bev_on_new_domain=1776797230_KKmE2MPABYjMTzwz&set_everest_cookie_on_new_domain=1776797229.EAYjVlMDU4YTQxMTA5OT.avGC8Xz-NKOetkvjxPDv0QzwxblIexDsUiWpxelMv_k',
      spotahome: 'https://www.spotahome.com/porto/for-rent:apartments/1553828',
      flatio: 'https://www.flatio.es/alquiler/piso/127332-matosinhos',
    },
    price: '2,250',
    name: 'Matosinhos',
    subtitle: 'Coastal Premium Living',
    location: 'Matosinhos, Porto',
    description:
      "Located in Matosinhos, Porto's most premium area, this former law firm was masterfully transformed into a top-tier residence. It features a spacious open-plan design and a signature glass-walled office, blending architectural excellence with an amazing view over the iconic Leixões harbor. A sophisticated, sun-drenched sanctuary just steps from the beach and city life.",
    longDescription:
      "Located in Matosinhos, Porto's most premium area, this former law firm was masterfully transformed into a top-tier residence. It features a spacious open-plan design and a signature glass-walled office, blending architectural excellence with an amazing view over the iconic Leixões harbor. A sophisticated, sun-drenched sanctuary just steps from the beach and city life.",
    tags: [
      { type: 'people', count: 3 },
      'Premium Location',
      'Top-Tier Architectural Design and Furniture',
      'Amazing View',
      'Amenity-Rich',
      'Modern',
      'Fully Furnished & Equipped',
      'Quiet & Soundproof',
      'Double-Glazed Windows',
    ],
    specs: {
      area: '155',
      beds: '2',
      baths: '2',
      type: 'Apartment',
      status: 'For Sale',
      year: '2022',
      yearLabel: 'Renovation Year',
      floor: '5',
      rooms: '6',
      garage: 'N/I',
    },
    image: '/images/Website.images/apt.photos/matosinhos.apt/1.webp',
    gallery: Array.from({ length: 19 }, (_, i) => `/images/Website.images/apt.photos/matosinhos.apt/${i + 1}.webp`),
    moreDetails: {
      intro: [
        'Fully furnished and equipped apartment, with excellent luminosity and a large open space area that integrates the living room, dining area, and kitchen, creating a modern, comfortable, and functional environment.',
        'The apartment includes an independent glass-walled office, ideal for teleworking, allowing a clear separation between professional and personal life.',
        'Premium location, a few minutes\' walk from the beach, metro, restaurants, and all services.',
        'Perfect for professionals, expatriates, or temporary stays with a high level of comfort, with clear, simple conditions and no surprises.',
      ],
      characteristics: [
        'Flexible lease from 1 to 12 months',
        'Fully furnished and equipped apartment',
        'Air conditioning, heating and double-glazed Windows',
        'High-speed internet and television',
        'Fortnightly cleaning included',
        'Expenses included up to €150/month (water, electricity, and internet)',
      ],
      composition: [
        '1 bedroom with double bed and built-in wardrobe',
        '1 bedroom with single bed, wardrobe, and work area',
        'Independent office (ideal for teleworking)',
        'Bright living room with dining area',
        'Fully equipped kitchen (stove, oven, microwave, refrigerator, dishwasher)',
        'Laundry area with washing machine and dryer',
        '2 full bathrooms with shower',
      ],
      highlights: [
        'Excellent natural luminosity',
        'Modern and functional design',
        'Double-glazed windows for thermal comfort',
        'Open views over the city and the Port of Leixões',
        'Bed linen and towels included',
      ],
      conditions: [
        'Deposit: 1 month (returned up to 30 days after departure)',
        'Administrative fee: €200 (one-time payment at the start of the contract)',
        'Fixed-term contract (not automatically renewable)',
      ],
    },
  },
  {
    id: 3,
    slug: 'alegria-apartment',
    mapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3004.4741844462674!2d-8.606274522915147!3d41.14600327133167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2464ef75aa9125%3A0x9f0fae5dc7c9639b!2s4000-041%20Porto!5e0!3m2!1spt-PT!2spt!4v1777896592568!5m2!1spt-PT!2spt',
    bookingLinks: {
      idealista: 'https://www.idealista.pt/imovel/34305390/',
      airbnb: 'https://www.airbnb.com/users/profile/1470751082133656177?previous_page_name=PdpHomeMarketplace&locale=en&_set_bev_on_new_domain=1776797230_KKmE2MPABYjMTzwz&set_everest_cookie_on_new_domain=1776797229.EAYjVlMDU4YTQxMTA5OT.avGC8Xz-NKOetkvjxPDv0QzwxblIexDsUiWpxelMv_k',
      spotahome: 'https://www.spotahome.com/porto/for-rent:apartments/1478660',
      flatio: 'https://www.flatio.es/alquiler/piso/120807-oporto',
    },
    price: '1,400',
    name: 'Alegria',
    subtitle: 'Heart of Porto Residence',
    location: 'Rua da Alegria, Porto',
    description:
      "A sleek, minimalist and renewed apartment located in the heart of Porto, on Rua da Alegria. This residence brings a modern edge to the city center, perfectly balancing Porto's traditional heritage with contemporary design. Its privileged location is only a 2-minute walk from Rua Santa Catarina, a hub that aggregates everything from premium retail and local boutiques to diverse restaurants, cafés, and other amazing places.",
    longDescription:
      "A sleek, minimalist and renewed apartment located in the heart of Porto, on Rua da Alegria. This residence brings a modern edge to the city center, perfectly balancing Porto's traditional heritage with contemporary design. Its privileged location is only a 2-minute walk from Rua Santa Catarina, a hub that aggregates everything from premium retail and local boutiques to diverse restaurants, cafés, and other amazing places.",
    tags: [
      { type: 'people', count: 2 },
      'Privileged Location',
      'Modern',
      'Minimalist',
      'Cozy View',
      'Fully Furnished & Equipped',
      'Quiet & Soundproof',
      'Double-Glazed Windows',
    ],
    specs: {
      area: '44',
      beds: '1',
      baths: '1',
      type: 'Apartment',
      status: 'For Rent',
      year: '2025',
      yearLabel: 'Renovation Year',
      floor: '2',
      rooms: '4',
      garage: 'N/I',
    },
    image: '/images/Website.images/apt.photos/alegria.apt/1.webp',
    gallery: Array.from({ length: 14 }, (_, i) => `/images/Website.images/apt.photos/alegria.apt/${i + 1}.webp`),
    moreDetails: {
      intro: [
        'Fully furnished and equipped apartment with excellent natural light, ready to live in, with expenses included up to €150/month and fortnightly cleaning included.',
        'Fully renovated, furnished and equipped apartment, ideal for professionals, expatriates and digital nomads looking for a modern, functional and comfortable space in the center of Porto. Located on Rua da Alegria, in a central and quiet area, a few minutes\' walk from Rua de Santa Catarina and the Bolhão Market.',
        'The social area in open space integrates the living room, dining area and fully equipped kitchen, creating a bright, functional and comfortable environment.',
        'Ideal solution for professional stays with everything included, without additional concerns.',
      ],
      characteristics: [
        'Flexible lease from 1 to 12 months',
        'Fully furnished and equipped apartment',
        'Air conditioning, heating and double-glazed Windows',
        'High-speed internet and television',
        'Fortnightly cleaning included',
        'Expenses included up to €150/month (water, electricity, and internet)',
      ],
      composition: [
        '1 bedroom with double bed, built-in wardrobe and natural light',
        'Integrated workspace (ideal for teleworking)',
        'Open space social area with living room and dining zone',
        'Fully equipped kitchen (stove, oven, microwave, refrigerator, dishwasher)',
        'Laundry area with washing machine and dryer',
        '1 full bathroom with shower and contemporary finishes',
      ],
      highlights: [
        'Excellent natural luminosity',
        'Modern and functional design',
        'Double-glazed windows for thermal comfort',
        'Strategic location near Santa Catarina and Bolhão',
        'High comfort and quiet central area',
        'Bed linen and towels included',
      ],
      conditions: [
        'Deposit: 1 month (returned up to 30 days after departure)',
        'Administrative fee: €135 (one-time payment at the start of the contract)',
        'Fixed-term contract (not automatically renewable)',
      ],
    },
  },
]

export function getPropertyBySlug(slug) {
  return properties.find((p) => p.slug === slug) ?? null
}

export function getRelatedProperties(slug) {
  return properties.filter((p) => p.slug !== slug)
}
