export const properties = [
  {
    id: 1,
    slug: 'paranhos-apartment',
    mapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1501.3463993945666!2d-8.609939604577535!3d41.184867156661596!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd24643159ecaf3f%3A0xdff04d905b4d5e7d!2s4200-550%20Porto!5e0!3m2!1spt-PT!2spt!4v1777896555430!5m2!1spt-PT!2spt',
    bookingLinks: {
      idealista: 'https://www.idealista.pt/imovel/34457200/',
      airbnb: 'https://www.airbnb.com/users/profile/1470751082133656177?previous_page_name=PdpHomeMarketplace&locale=en&_set_bev_on_new_domain=1776797230_KKmE2MPABYjMTzwz&set_everest_cookie_on_new_domain=1776797229.EAYjVlMDU4YTQxMTA5OT.avGC8Xz-NKOetkvjxPDv0QzwxblIexDsUiWpxelMv_k',
      spotahome: 'https://www.spotahome.com/porto/for-rent:apartments/1491376',
      flatio: 'https://www.flatio.es/alquiler/piso/120808-oporto',
    },
    price: '1,400',
    name: 'Paranhos',
    ptName: 'Apartamento de Paranhos',
    subtitle: 'Ultra-Modern Urban Apartment',
    ptSubtitle: 'Apartamento Urbano Ultra-Moderno',
    location: 'Paranhos, Porto',
    description:
      'One of the most modern-looking buildings you will find in Porto, embodying a minimalistic approach that combines a clean architectural exterior with a functional, elegant, and high-standard interior. Located in Paranhos, a privileged location due to its direct access to the city center, the University Polo, shopping hubs, major healthcare facilities, and diverse dining options.',
    ptDescription:
      'Um dos edifícios mais contemporâneos que encontrará no Porto, com uma abordagem minimalista que conjuga um exterior clean com um interior funcional, elegante e de elevado padrão. Situado em Paranhos, uma localização privilegiada pelo acesso direto ao centro da cidade, ao Polo Universitário, a centros comerciais, às principais unidades de saúde e a uma diversificada oferta gastronómica.',
    longDescription:
      'One of the most modern-looking buildings you will find in Porto, embodying a minimalistic approach that combines a clean architectural exterior with a functional, elegant, and high-standard interior. Located in Paranhos, a privileged location due to its direct access to the city center, the University Polo, shopping hubs, major healthcare facilities, and diverse dining options.',
    tags: [
      { type: 'people', count: 2 },
      'Garage',
      'Privileged Location',
      'Wide Space',
      'Ultra-Modern',
      'Fully Furnished & Equipped',
      'Quiet & Soundproof',
      'Double-Glazed Windows',
    ],
    ptTags: [
      { type: 'people', count: 2 },
      'Garagem',
      'Localização Privilegiada',
      'Espaço Amplo',
      'Ultra-Moderno',
      'Totalmente Mobilado e Equipado',
      'Privacidade e Isolamento',
      'Janelas de Vidro Duplo',
    ],
    specs: {
      area: '60',
      beds: '1',
      baths: '1',
      type: 'Apartment',
      ptType: 'Apartamento',
      status: 'For Rent',
      year: '2023',
      floor: '3',
      rooms: '4',
      garage: '1 Spot',
      ptGarage: '1 Lugar',
    },
    image: '/images/website.images/apt.photos/paranhos.apt/1.webp',
    gallery: Array.from({ length: 20 }, (_, i) => `/images/website.images/apt.photos/paranhos.apt/${i + 1}.webp`),
    moreDetails: {
      intro: [
        'Fully furnished and equipped apartment, ideal for professionals, expatriates, international students, and digital nomads looking for comfort, functionality, and a turnkey solution in Porto.',
        'Located in Paranhos, in a central and dynamic area with a strong university presence, close to hospitals, faculties, commerce, and public transport (metro and buses), allowing quick access to the city center.',
        'The social area in open space integrates the living room, dining area, and a space dedicated to teleworking by the window, with excellent natural light throughout the day.',
        'Perfect for those looking for a flexible housing solution, with services included, parking, and excellent connection to the entire city of Porto.',
      ],
      characteristics: [
        'Flexible lease from 1 to 12 months',
        'Fully furnished and equipped apartment',
        'Air conditioning, heating and double-glazed Windows',
        'High-speed internet and television',
        'Fortnightly cleaning included',
        'Expenses included up to €150/month (water, electricity, and internet)',
      ],
      composition: [
        '1 bedroom with double bed and built-in wardrobes with interior lighting',
        'Dedicated teleworking space by the window',
        'Open space social area with living room and dining zone',
        'Fully equipped kitchen (stove, oven, refrigerator, dishwasher)',
        'Laundry area with washing machine and dryer',
        '1 full bathroom with shower and contemporary finishes',
        '1 parking space included in the building',
      ],
      highlights: [
        'Excellent natural luminosity',
        'Modern and functional design',
        'Double-glazed windows for thermal comfort',
        'Strategic location near the University Campus and hospitals',
        'Bed linen and towels included',
      ],
      conditions: [
        'Deposit: 1 month (returned up to 30 days after departure)',
        'Administrative fee: €135 (one-time payment at the start of the contract)',
        'Fixed-term contract (not automatically renewable)',
      ],
    },
    ptMoreDetails: {
      intro: [
        'Apartamento totalmente mobilado e equipado, pensado para profissionais, expatriados, estudantes internacionais e nómadas digitais que procuram conforto, funcionalidade e uma solução pronta a habitar no Porto.',
        'Situado em Paranhos, numa zona central e dinâmica, com forte presença universitária, próxima de hospitais, faculdades, comércio e transportes públicos (metro e autocarros), com fácil e rápido acesso ao centro da cidade.',
        'A zona social em open space integra a sala de estar, a zona de refeições e um espaço dedicado ao teletrabalho junto à janela, beneficiando de excelente luminosidade natural ao longo de todo o dia.',
        'Ideal para quem procura uma solução habitacional flexível, com serviços incluídos, estacionamento e uma excelente ligação a toda a cidade do Porto.',
      ],
      characteristics: [
        'Contrato flexível de 1 a 12 meses',
        'Apartamento totalmente mobilado e equipado',
        'Ar condicionado, aquecimento e janelas de vidro duplo',
        'Internet de alta velocidade e televisão',
        'Limpeza quinzenal incluída',
        'Despesas incluídas até 150 €/mês (água, eletricidade e internet)',
      ],
      composition: [
        '1 quarto com cama de casal e roupeiros embutidos com iluminação interior',
        'Espaço para teletrabalho junto à janela',
        'Zona social em open space com sala de estar e zona de refeições',
        'Cozinha totalmente equipada (fogão, forno, frigorífico, máquina de lavar louça)',
        'Zona de lavandaria com máquina de lavar roupa e secadora',
        '1 casa de banho completa com duche e acabamentos contemporâneos',
        '1 lugar de estacionamento incluído no edifício',
      ],
      highlights: [
        'Excelente luminosidade natural',
        'Design moderno e funcional',
        'Janelas de vidro duplo para conforto térmico',
        'Localização estratégica junto ao Campus Universitário e hospitais',
        'Roupa de cama e toalhas incluídas',
        'Jogo de cama incluído',
      ],
      conditions: [
        'Depósito: 1 mês (devolvido até 30 dias após saída)',
        'Taxa administrativa: 135 € (pagamento único no início do contrato)',
        'Contrato a termo certo (não renovável automaticamente)',
      ],
    },
  },
  {
    id: 2,
    slug: 'matosinhos-apartment',
    mapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1814.2561436565452!2d-8.692038358446707!3d41.18608973309975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd246f31b43ed1f5%3A0xa60c6b18bce815c8!2s4450-038%20Matosinhos!5e0!3m2!1spt-PT!2spt!4v1777896408666!5m2!1spt-PT!2spt',
    bookingLinks: {
      idealista: 'https://www.idealista.pt/imovel/34888612/',
      airbnb: 'https://www.airbnb.com/users/profile/1470751082133656177?previous_page_name=PdpHomeMarketplace&locale=en&_set_bev_on_new_domain=1776797230_KKmE2MPABYjMTzwz&set_everest_cookie_on_new_domain=1776797229.EAYjVlMDU4YTQxMTA5OT.avGC8Xz-NKOetkvjxPDv0QzwxblIexDsUiWpxelMv_k',
      spotahome: 'https://www.spotahome.com/porto/for-rent:apartments/1553828',
      flatio: 'https://www.flatio.es/alquiler/piso/127332-matosinhos',
    },
    price: '2,250',
    name: 'Matosinhos',
    ptName: 'Apartamento de Matosinhos',
    subtitle: 'Coastal Premium Living',
    ptSubtitle: 'Vida Premium à Beira-Mar',
    location: 'Matosinhos, Porto',
    description:
      "Located in Matosinhos, Porto's most premium area, this former office space was masterfully renewed and transformed into a top-tier residence. It features a spacious open-plan design and a signature glass-walled office, blending architectural excellence with an amazing view over the iconic Leixões harbor. A sophisticated, sun-drenched sanctuary just steps from the beach and city life.",
    ptDescription:
      "Localizado em Matosinhos, a localidade mais premium do Porto, este antigo espaço de escritório foi completamente renovado e transformado em uma residência ultra-premium. Este apartamento conta com um design open-plan espaçoso, e um espaço de escritório em vidro, conjugando um elevado nível de excelência arquitetónica com uma vista deslumbrante sobre o icónico Porto de Leixões. Conta com bastante luz natural e oferece simultaneamente a serenidade da uma zona costeira e o urbanismo das cidades.",
    longDescription:
      "Located in Matosinhos, Porto's most premium area, this former office space was masterfully transformed into a top-tier residence. It features a spacious open-plan design and a signature glass-walled office, blending architectural excellence with an amazing view over the iconic Leixões harbor. A sophisticated, sun-drenched sanctuary just steps from the beach and city life.",
    tags: [
      { type: 'people', count: 3 },
      'Premium Location',
      'Top-Tier Architectural Design and Furniture',
      'Amazing View',
      'Amenity-Rich',
      'Modern',
      'Fully Furnished & Equipped',
      'Quiet & Soundproof',
      'Double-Glazed Windows',
    ],
    ptTags: [
      { type: 'people', count: 3 },
      'Localização Premium',
      'Design e Mobiliário de Excelência',
      'Vista Deslumbrante',
      'Rico em Comodidades',
      'Moderno',
      'Totalmente Mobilado e Equipado',
      'Privacidade e Isolamento',
      'Janelas de Vidro Duplo',
    ],
    specs: {
      area: '155',
      beds: '2',
      baths: '2',
      type: 'Apartment',
      ptType: 'Apartamento',
      status: 'For Sale',
      year: '2022',
      yearLabel: 'Renovation Year',
      floor: '5',
      rooms: '6',
      garage: 'N/I',
    },
    image: '/images/website.images/apt.photos/matosinhos.apt/1.webp',
    gallery: Array.from({ length: 19 }, (_, i) => `/images/website.images/apt.photos/matosinhos.apt/${i + 1}.webp`),
    moreDetails: {
      intro: [
        'Fully furnished and equipped apartment, with excellent luminosity and a large open space area that integrates the living room, dining area, and kitchen, creating a modern, comfortable, and functional environment.',
        'The apartment includes an independent glass-walled office, ideal for teleworking, allowing a clear separation between professional and personal life.',
        'Premium location, a few minutes\' walk from the beach, metro, restaurants, and several other services.',
        'Perfect for professionals, expatriates, or temporary stays with a high level of comfort, with clear, simple conditions and no surprises.',
      ],
      characteristics: [
        'Flexible lease from 1 to 12 months',
        'Fully furnished and equipped apartment',
        'Air conditioning, heating and double-glazed Windows',
        'High-speed internet and television',
        'Fortnightly cleaning included',
        'Expenses included up to €150/month (water, electricity, and internet)',
      ],
      composition: [
        '1 bedroom with double bed and built-in wardrobe',
        '1 bedroom with single bed, wardrobe, and work area',
        'Independent office (ideal for teleworking)',
        'Bright living room with dining area',
        'Fully equipped kitchen (stove, oven, microwave, refrigerator, dishwasher)',
        'Laundry area with washing machine and dryer',
        '2 full bathrooms with shower',
      ],
      highlights: [
        'Excellent natural luminosity',
        'Modern and functional design',
        'Double-glazed windows for thermal comfort',
        'Open views over the city and the Port of Leixões',
        'Bed linen and towels included',
      ],
      conditions: [
        'Deposit: 1 month (returned up to 30 days after departure)',
        'Administrative fee: €200 (one-time payment at the start of the contract)',
        'Fixed-term contract (not automatically renewable)',
      ],
    },
    ptMoreDetails: {
      intro: [
        'Apartamento totalmente mobilado e equipado, com excelente luminosidade e uma ampla zona social em open space que integra a sala de estar, a zona de refeições e a cozinha, criando um ambiente moderno, confortável e funcional.',
        'O apartamento dispõe de um escritório independente em vidro, ideal para teletrabalho, permitindo uma separação clara entre a vida profissional e pessoal.',
        'Localização premium, a poucos minutos a pé da praia, do metro, de restaurantes e de diversos outros serviços.',
        'Ideal para profissionais, expatriados ou estadias temporárias de elevado conforto, com condições claras e simples, sem surpresas.',
      ],
      characteristics: [
        'Contrato flexível de 1 a 12 meses',
        'Apartamento totalmente mobilado e equipado',
        'Ar condicionado, aquecimento e janelas de vidro duplo',
        'Internet de alta velocidade e televisão',
        'Limpeza quinzenal incluída',
        'Despesas incluídas até 150 €/mês (água, eletricidade e internet)',
      ],
      composition: [
        '1 quarto com cama de casal e roupeiro embutido',
        '1 quarto com cama individual, roupeiro e zona de trabalho',
        'Escritório independente (espaço para teletrabalho)',
        'Sala de estar luminosa com zona de refeições',
        'Cozinha totalmente equipada (fogão, forno, micro-ondas, frigorífico, máquina de lavar louça)',
        'Zona de lavandaria com máquina de lavar roupa e secadora',
        '2 casas de banho completas com duche',
      ],
      highlights: [
        'Excelente luminosidade natural',
        'Design moderno e funcional',
        'Janelas de vidro duplo para conforto térmico',
        'Vista aberta sobre a cidade e o Porto de Leixões',
        'Roupa de cama e toalhas incluídas',
        'Jogo de cama incluído',
      ],
      conditions: [
        'Depósito: 1 mês (devolvido até 30 dias após saída)',
        'Taxa administrativa: 200 € (pagamento único no início do contrato)',
        'Contrato a termo certo (não renovável automaticamente)',
      ],
    },
  },
  {
    id: 3,
    slug: 'alegria-apartment',
    mapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3004.4741844462674!2d-8.606274522915147!3d41.14600327133167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2464ef75aa9125%3A0x9f0fae5dc7c9639b!2s4000-041%20Porto!5e0!3m2!1spt-PT!2spt!4v1777896592568!5m2!1spt-PT!2spt',
    bookingLinks: {
      idealista: 'https://www.idealista.pt/imovel/34305390/',
      airbnb: 'https://www.airbnb.com/users/profile/1470751082133656177?previous_page_name=PdpHomeMarketplace&locale=en&_set_bev_on_new_domain=1776797230_KKmE2MPABYjMTzwz&set_everest_cookie_on_new_domain=1776797229.EAYjVlMDU4YTQxMTA5OT.avGC8Xz-NKOetkvjxPDv0QzwxblIexDsUiWpxelMv_k',
      spotahome: 'https://www.spotahome.com/porto/for-rent:apartments/1478660',
      flatio: 'https://www.flatio.es/alquiler/piso/120807-oporto',
    },
    price: '1,400',
    name: 'Alegria',
    ptName: 'Apartamento de Alegria',
    subtitle: 'Heart of Porto Residence',
    ptSubtitle: 'No Coração do Porto',
    location: 'Rua da Alegria, Porto',
    description:
      "A sleek, minimalist and renewed apartment located in the heart of Porto, on Rua da Alegria. This residence brings a modern edge to the city center, perfectly balancing Porto's traditional heritage with contemporary design. Its location is privileged, being just a 2-minute walk from Rua de Santa Catarina, the city's commercial epicenter, which features local boutiques, restaurants, a shopping mall, international brands, cafes, and much more.",
    ptDescription:
      "Um apartamento moderno, minimalista e renovado, situado no coração do Porto, na Rua da Alegria. Esta residência traz um toque contemporâneo ao centro da cidade, equilibrando o caráter arquitetónico do Porto com um design mais moderno. A sua localização é privilegiada, ficando a apenas 2 minutos a pé da Rua de Santa Catarina, o epicentro comercial da cidade que conta boutiques locais, restaurantes, um shopping, marcas internacionais, cafés e muito mais.",
    longDescription:
      "A sleek, minimalist and renewed apartment located in the heart of Porto, on Rua da Alegria. This residence brings a modern edge to the city center, perfectly balancing Porto's traditional heritage with contemporary design. Its privileged location is only a 2-minute walk from Rua Santa Catarina, a hub that aggregates everything from premium retail and local boutiques to diverse restaurants, cafés, and other amazing places.",
    tags: [
      { type: 'people', count: 2 },
      'Privileged Location',
      'Modern',
      'Minimalist',
      'Cozy View',
      'Fully Furnished & Equipped',
      'Quiet & Soundproof',
      'Double-Glazed Windows',
    ],
    ptTags: [
      { type: 'people', count: 2 },
      'Localização Privilegiada',
      'Moderno',
      'Minimalista',
      'Vista Acolhedora',
      'Totalmente Mobilado e Equipado',
      'Privacidade e Isolamento',
      'Janelas de Vidro Duplo',
    ],
    specs: {
      area: '44',
      beds: '1',
      baths: '1',
      type: 'Apartment',
      ptType: 'Apartamento',
      status: 'For Rent',
      year: '2025',
      yearLabel: 'Renovation Year',
      floor: '2',
      rooms: '4',
      garage: 'N/I',
    },
    image: '/images/website.images/apt.photos/alegria.apt/1.webp',
    gallery: Array.from({ length: 14 }, (_, i) => `/images/website.images/apt.photos/alegria.apt/${i + 1}.webp`),
    moreDetails: {
      intro: [
        'Fully furnished and equipped apartment with excellent natural light, ready to live in, with expenses included up to €150/month and fortnightly cleaning included.',
        'Fully renovated, furnished and equipped apartment, ideal for professionals, expatriates and digital nomads looking for a modern, functional and comfortable space in the center of Porto. Located on Rua da Alegria, in a central and quiet area, a few minutes\' walk from Rua de Santa Catarina and the Bolhão Market.',
        'The social area in open space integrates the living room, dining area and fully equipped kitchen, creating a bright, functional and comfortable environment.',
        'Ideal solution for professional stays with everything included, without additional concerns.',
      ],
      characteristics: [
        'Flexible lease from 1 to 12 months',
        'Fully furnished and equipped apartment',
        'Air conditioning, heating and double-glazed Windows',
        'High-speed internet and television',
        'Fortnightly cleaning included',
        'Expenses included up to €150/month (water, electricity, and internet)',
      ],
      composition: [
        '1 bedroom with double bed, built-in wardrobe and natural light',
        'Integrated workspace (ideal for teleworking)',
        'Open space social area with living room and dining zone',
        'Fully equipped kitchen (stove, oven, microwave, refrigerator, dishwasher)',
        'Laundry area with washing machine and dryer',
        '1 full bathroom with shower and contemporary finishes',
      ],
      highlights: [
        'Excellent natural luminosity',
        'Modern and functional design',
        'Double-glazed windows for thermal comfort',
        'Strategic location near Santa Catarina and Bolhão',
        'High comfort and quiet central area',
        'Bed linen and towels included',
      ],
      conditions: [
        'Deposit: 1 month (returned up to 30 days after departure)',
        'Administrative fee: €135 (one-time payment at the start of the contract)',
        'Fixed-term contract (not automatically renewable)',
      ],
    },
    ptMoreDetails: {
      intro: [
        'Apartamento totalmente mobilado e equipado, com excelente luminosidade natural, pronto a habitar, com despesas incluídas até 150 €/mês e limpeza quinzenal incluída.',
        'Apartamento totalmente renovado, mobilado e equipado, ideal para profissionais, expatriados e nómadas digitais que procuram um espaço moderno, funcional e confortável no centro do Porto. Situado na Rua da Alegria, numa zona central e tranquila, a poucos minutos a pé da Rua de Santa Catarina e do Mercado do Bolhão.',
        'A zona social em open space desta residência integra a sala de estar, a zona de refeições e a cozinha totalmente equipada, criando um ambiente luminoso, funcional e acolhedor.',
        'Uma solução ideal para estadias profissionais com tudo incluído, sem preocupações adicionais.',
      ],
      characteristics: [
        'Contrato flexível de 1 a 12 meses',
        'Apartamento totalmente mobilado e equipado',
        'Ar condicionado, aquecimento e janelas de vidro duplo',
        'Internet de alta velocidade e televisão',
        'Limpeza quinzenal incluída',
        'Despesas incluídas até 150 €/mês (água, eletricidade e internet)',
      ],
      composition: [
        '1 quarto com cama de casal, roupeiro embutido e luz natural',
        'Espaço para teletrabalho integrado',
        'Zona social em open space com sala de estar e zona de refeições',
        'Cozinha totalmente equipada (fogão, forno, micro-ondas, frigorífico, máquina de lavar louça)',
        'Zona de lavandaria com máquina de lavar roupa e secadora',
        '1 casa de banho completa com duche e acabamentos contemporâneos',
      ],
      highlights: [
        'Excelente luminosidade natural',
        'Design moderno e funcional',
        'Janelas de vidro duplo para conforto térmico',
        'Localização estratégica junto à Santa Catarina e ao Mercado do Bolhão',
        'Elevado conforto numa zona central e tranquila',
        'Roupa de cama e toalhas incluídas',
        'Jogo de cama incluído',
      ],
      conditions: [
        'Depósito: 1 mês (devolvido até 30 dias após saída)',
        'Taxa administrativa: 135 € (pagamento único no início do contrato)',
        'Contrato a termo certo (não renovável automaticamente)',
      ],
    },
  },
]

export function getPropertyBySlug(slug) {
  return properties.find((p) => p.slug === slug) ?? null
}

export function getRelatedProperties(slug) {
  return properties.filter((p) => p.slug !== slug)
}
